title: Goabaone Sehurutshe
description: Actuarial Developer & Data Engineer specializing in London Specialty Market Analytics & Risk Modeling
baseurl: ""
url: "https://gsehurut.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - .vscode/

# Site author information
author:
  name: Goabaone Sehurutshe
  email: goabaonesehurutshe@gmail.com
  location: London, United Kingdom
  social:
    linkedin: goabaone-sehurutshe-572606127
    github: GSehurut
    twitter: ""
